services:
  mysql:
    image: mysql:8.4
    container_name: ps-cafe-mysql
    environment:
      MYSQL_DATABASE: ps_cafe
      MYSQL_USER: ps_user
      MYSQL_PASSWORD: ps_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - ps_cafe_mysql:/var/lib/mysql
volumes:
  ps_cafe_mysql:
